bugfix - missing font causing crash
Calligraphy﹕ Can't create asset from fonts/Roboto-Roboto.ttf. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: Font asset not found fonts/Roboto-Roboto.ttf